version: '3.3'
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
      - FLARESOLVERR_URL=http://flaresolverr:8191
    volumes:
      - /home/dockeruser/docker/jackett/jackett-data:/config
      - /home/dockeruser/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=warning
      - TZ=Europe/Kyiv
      - MAX_CONCURRENT=3
      - CAPTCHA_SOLVER=none
    volumes:
      - ./flaresolverr:/config
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
